export const vocabulary = [
  {
    type: "word",
    english: "abandon",
    polish: "porzucić",
    level: "B2",
    pos: "verb",
    pos_pl: "czasownik",
    prefix: "to",
    emoji: "👋",
    examples: [
      "They were forced to {abandon} the car.",
      "He {abandoned} his family.",
    ],
  },
  {
    type: "word",
    english: "accurate",
    polish: "dokładny",
    level: "B2",
    pos: "adjective",
    pos_pl: "przymiotnik",
    prefix: "",
    emoji: "🎯",
    examples: [
      "The description of the suspect was very {accurate}.",
      "We need to get an {accurate} estimate of the cost.",
    ],
  },
  {
    type: "word",
    english: "anxiety",
    polish: "niepokój",
    level: "B2",
    pos: "noun",
    pos_pl: "rzeczownik",
    prefix: "-",
    emoji: "😟",
    examples: [
      "High levels of {anxiety} can affect your health.",
      "He suffers from a crippling {anxiety} about flying.",
    ],
  },
  {
    type: "word",
    english: "approach",
    polish: "podejście",
    level: "B2",
    pos: "noun",
    pos_pl: "rzeczownik",
    prefix: "an",
    emoji: "🚶‍♂️",
    examples: [
      "We need to find a new {approach} to the problem.",
      "Winter is {approaching}.",
    ],
  },
  {
    type: "word",
    english: "concept",
    polish: "pojęcie",
    level: "B2",
    pos: "noun",
    pos_pl: "rzeczownik",
    prefix: "a",
    emoji: "💡",
    examples: [
      "It is a difficult {concept} to grasp.",
      "She developed a new {concept} for the product.",
    ],
  },
  {
    type: "phrasal verb",
    english: "back down",
    polish: "wycofać się",
    level: "B2",
    pos: "phrasal verb",
    pos_pl: "czas. frazowy",
    prefix: "to",
    emoji: "退",
    examples: [
      "She refused to {back down} on a point of principle.",
      "He finally {backed down} and apologized.",
    ],
  },
  {
    type: "phrasal verb",
    english: "bring up",
    polish: "wychowywać, poruszyć temat",
    level: "B2",
    pos: "phrasal verb",
    pos_pl: "czas. frazowy",
    prefix: "to",
    emoji: "💬",
    examples: [
      "She was {brought up} by her grandparents.",
      "Don't {bring up} the subject of money again.",
    ],
  },
  {
    type: "phrasal verb",
    english: "call off",
    polish: "odwołać",
    level: "B2",
    pos: "phrasal verb",
    pos_pl: "czas. frazowy",
    prefix: "to",
    emoji: "❌",
    examples: [
      "They had to {call off} the meeting due to the storm.",
      "The wedding was {called off} at the last minute.",
    ],
  },
  {
    type: "phrasal verb",
    english: "figure out",
    polish: "zrozumieć, rozwiązać",
    level: "B2",
    pos: "phrasal verb",
    pos_pl: "czas. frazowy",
    prefix: "to",
    emoji: "💡",
    examples: [
      "I can't {figure out} how to do this.",
      "We need to {figure out} a way to solve this problem.",
    ],
  },
  {
    type: "phrasal verb",
    english: "give up",
    polish: "poddać się, rzucić",
    level: "B2",
    pos: "phrasal verb",
    pos_pl: "czas. frazowy",
    prefix: "to",
    emoji: "🏳️",
    examples: [
      "He {gave up} smoking five years ago.",
      "Don't {give up}, you're almost there!",
    ],
  },
];

export const uiStrings = {
  en: {
    title: "Vocabulary Trainer",
    subtitle: "Oxford Words & Phrasals",
    direction: "Direction",
    difficulty: "Difficulty",
    hard: "Hard",
    medium: "Medium",
    easy: "Easy",
    contentType: "Content Type",
    word: "Word",
    phrasalVerb: "Phrasal Verb",
    level: "Filter by Level",
    pos: "Filter by Part of Speech",
    verb: "Verb",
    noun: "Noun",
    adjective: "Adjective",
    apply: "Apply Settings & Restart",
    check: "Check",
    next: "Next Word",
    score: "Score",
    from: "from",
    correct: "Correct!",
    incorrect: "Incorrect. The correct answer is:",
    noWords: "No words match your filters.",
    changeSettings: "Please change your settings and try again.",
    sessionComplete: "Session Complete!",
    finalScore: "Final Score:",
    answerPlaceholder: "Type your answer here...",
    mode: "Game Mode",
    standard: "Standard",
    infinite: "Infinite",
    restart: "Restart",
  },
  pl: {
    title: "Trener Słownictwa",
    subtitle: "Słowa i Czasowniki Frazowe Oxford",
    direction: "Kierunek",
    difficulty: "Poziom trudności",
    hard: "Trudny",
    medium: "Średni",
    easy: "Łatwy",
    contentType: "Rodzaj Treści",
    word: "Słowo",
    phrasalVerb: "Czasownik frazowy",
    level: "Filtruj po poziomie",
    pos: "Filtruj po części mowy",
    verb: "Czasownik",
    noun: "Rzeczownik",
    adjective: "Przymiotnik",
    apply: "Zastosuj i zrestartuj",
    check: "Sprawdź",
    next: "Następne słowo",
    score: "Wynik",
    from: "z",
    correct: "Prawidłowo!",
    incorrect: "Nieprawidłowo. Poprawna odpowiedź to:",
    noWords: "Brak słów pasujących do filtrów.",
    changeSettings: "Zmień ustawienia i spróbuj ponownie.",
    sessionComplete: "Sesja zakończona!",
    finalScore: "Końcowy wynik:",
    answerPlaceholder: "Wpisz odpowiedź tutaj...",
    mode: "Tryb Gry",
    standard: "Standardowy",
    infinite: "Nieskończony",
    restart: "Restartuj",
  },
};
